labelPRBasedOnFilePath:
  ci:
    - .github/*
    - .github/**/*

  dependencies:
    - lib/website/package.json
    - lib/website/pnpm-lock.yaml

  website:
    - lib/website/*
    - lib/website/**/*

firstPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines.

verifyTitles:
  titleRegexp: ^(feat|feat!|fix|fix!|docs|refactor|refactor!|test|chore|build)\((ci|main|docs|deps|deps-dev|website|infrastructure)\):.*
  alwaysUsePrTitle: true
  validateEitherPrOrSingleCommitTitle: true
  statusTitle: "Title Validator"
  successMessage: "Validation successful!"
  failureMessage: "Wrong ${type} title: ${title}"
