name: "Test Composite Action"
description: "A simple composite action to demonstrate inputs and steps"

inputs:
  test:
    description: "Test input"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Test
      shell: bash
      run: |
        echo "Test input: ${{ inputs.test }}"
