name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: ./.github/workflows/actions/@walle/deploy-github-pages
        timeout-minutes: 5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
